# Generated by Django 5.0.4 on 2024-04-25 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField()),
                ('phone_number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DealerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('year', models.IntegerField()),
                ('color', models.TextField()),
                ('description', models.TextField()),
                ('image', models.TextField(null=True)),
                ('liked', models.BooleanField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_cars', to='dealer.dealer')),
            ],
        ),
    ]
