# Generated by Django 5.0.4 on 2024-04-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealercar',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
