# Generated by Django 5.0.4 on 2024-04-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
